import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const COMPONENTS_PATH = path.join(ROOT, 'src', 'generated', 'components.json');
const OUT_DIR = path.join(ROOT, 'src', 'generated');
const ENUMS_FILE = path.join(OUT_DIR, 'enums.ts');
const INTERFACES_FILE = path.join(OUT_DIR, 'components.ts');

interface SchemaProperty {
  type?: string;
  enum?: string[];
  items?: SchemaProperty;
  anyOf?: SchemaProperty[];
  properties?: Record<string, SchemaProperty>;
  required?: string[];
}

interface Parameter {
  name: string;
  schema: SchemaProperty;
}

interface Component {
  name: string;
  module: string;
  type: string;
  executionModes: string[];
  inputs: {
    parameters: Parameter[];
  };
  outputs: {
    response: Parameter[];
  };
  configs: SchemaProperty;
}

function toPascalCase(str: string): string {
  return str
    .split('_')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase())
    .join('');
}

function schemaToTsType(schema: SchemaProperty): string {
  if (!schema || !schema.type) return 'unknown';

  if (schema.enum) {
    return schema.enum.map((v) => `'${v}'`).join(' | ');
  }

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'bigint':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'object':
      if (schema.properties && Object.keys(schema.properties).length > 0) {
        const props = Object.entries(schema.properties).map(([key, val]) => {
          const optional = !(schema.required || []).includes(key);
          return `${key}${optional ? '?' : ''}: ${schemaToTsType(val)}`;
        });
        return `{ ${props.join('; ')} }`;
      }
      return 'Record<string, unknown>';
    case 'array':
      if (schema.items) {
        if (schema.items.anyOf) {
          return `Array<${schema.items.anyOf.map((s) => schemaToTsType(s)).join(' | ')}>`;
        }
        if (schema.items.type) {
          const itemType = schemaToTsType(schema.items);
          const needsParens = itemType.includes(' | ');
          return needsParens ? `(${itemType})[]` : `${itemType}[]`;
        }
      }
      return 'unknown[]';
    default:
      return 'unknown';
  }
}

function generateInputInterface(component: Component): string {
  const name = toPascalCase(component.module);
  const params = component.inputs?.parameters || [];

  if (params.length === 0) {
    return `export type ${name}Input = Record<string, never>;`;
  }

  const fields = params.map((p) => {
    return `  ${p.name}: ${schemaToTsType(p.schema)};`;
  });

  return [
    `export interface ${name}Input {`,
    ...fields,
    '}',
  ].join('\n');
}

function generateOutputInterface(component: Component): string {
  const name = toPascalCase(component.module);
  const response = component.outputs?.response || [];

  if (response.length === 0) {
    return `export type ${name}Output = Record<string, never>;`;
  }

  const fields = response.map((r) => {
    return `  ${r.name}: ${schemaToTsType(r.schema)};`;
  });

  return [
    `export interface ${name}Output {`,
    ...fields,
    '}',
  ].join('\n');
}

function generateConfigInterface(component: Component): string {
  const name = toPascalCase(component.module);
  const props = component.configs?.properties || {};

  if (Object.keys(props).length === 0) {
    return `export type ${name}Config = Record<string, never>;`;
  }

  const required = component.configs?.required || [];
  const fields = Object.entries(props).map(([key, val]) => {
    const optional = !required.includes(key);
    return `  ${key}${optional ? '?' : ''}: ${schemaToTsType(val as SchemaProperty)};`;
  });

  return [
    `export interface ${name}Config {`,
    ...fields,
    '}',
  ].join('\n');
}

function generate() {
  if (!fs.existsSync(COMPONENTS_PATH)) {
    console.error('components.json not found. Run fetch:components first.');
    process.exit(1);
  }

  const allComponents: Component[] = JSON.parse(fs.readFileSync(COMPONENTS_PATH, 'utf-8'));

  const executionModes = new Set<string>();
  const types = new Set<string>();
  const modules = new Set<string>();
  const componentModeComponents: Component[] = [];

  for (const c of allComponents) {
    (c.executionModes || []).forEach((m) => executionModes.add(m));

    const hasComponentMode = (c.executionModes || []).includes('COMPONENT');
    if (!hasComponentMode) continue;

    if (c.type) types.add(c.type);
    if (c.module) modules.add(c.module);
    componentModeComponents.push(c);
  }

  const sorted = componentModeComponents.sort((a, b) => a.module.localeCompare(b.module));

  // --- Generate enums file ---
  const enumLines = [
    '// This file is auto-generated by scripts/generate-components.ts',
    '// Do not edit manually.',
    '',
    'export enum ExecutionMode {',
    ...[...executionModes].sort().map((v) => `  ${v} = '${v}',`),
    '}',
    '',
    'export enum ComponentType {',
    ...[...types].sort().map((v) => `  ${v} = '${v}',`),
    '}',
    '',
    'export enum ComponentModule {',
    ...[...modules].sort().map((v) => `  ${v} = '${v}',`),
    '}',
    '',
  ];

  // --- Generate interfaces file ---
  const ifaceLines = [
    '// This file is auto-generated by scripts/generate-components.ts',
    '// Do not edit manually.',
    '',
    "import { ComponentModule } from './enums';",
    '',
  ];

  for (const c of sorted) {
    ifaceLines.push(generateInputInterface(c));
    ifaceLines.push('');
    ifaceLines.push(generateOutputInterface(c));
    ifaceLines.push('');
    ifaceLines.push(generateConfigInterface(c));
    ifaceLines.push('');
  }

  // Generate call interface with method overloads
  ifaceLines.push('export interface CallableComponents {');
  for (const c of sorted) {
    const name = toPascalCase(c.module);
    const hasInput = (c.inputs?.parameters || []).length > 0;
    const hasConfig = Object.keys(c.configs?.properties || {}).length > 0;

    const inputOptional = !hasInput && !hasConfig;
    const params = [`module: ComponentModule.${c.module}`];
    params.push(`input${inputOptional ? '?' : ''}: ${name}Input`);
    params.push(`config${hasConfig ? '' : '?'}: ${name}Config`);

    ifaceLines.push(`  call(${params.join(', ')}): Promise<${name}Output>;`);
  }
  ifaceLines.push('}');
  ifaceLines.push('');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(ENUMS_FILE, enumLines.join('\n'), 'utf-8');
  fs.writeFileSync(INTERFACES_FILE, ifaceLines.join('\n'), 'utf-8');

  console.log(`Generated ${path.relative(ROOT, ENUMS_FILE)} (${executionModes.size} execution modes, ${types.size} types, ${modules.size} modules)`);
  console.log(`Generated ${path.relative(ROOT, INTERFACES_FILE)} (${sorted.length} component interfaces)`);
}

generate();
