import * as fs from 'fs';
import * as path from 'path';
import dotenv from 'dotenv';

const ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'src', 'generated');
const OUT_FILE = path.join(OUT_DIR, 'env.ts');

function generate() {
  const result = dotenv.config({ path: path.join(ROOT, '.env') });

  if (result.error) {
    console.error('.env file not found');
    process.exit(1);
  }

  const vars = result.parsed!;
  const PREFIX = 'PUBLIC_';

  const publicVars = Object.entries(vars).filter(([key]) => key.startsWith(PREFIX));

  const lines = [
    '// This file is auto-generated by scripts/generate-env.ts',
    '// Do not edit manually.',
    `// Only variables prefixed with "${PREFIX}" are included.`,
    '',
  ];

  for (const [key, value] of publicVars) {
    const exportName = key.slice(PREFIX.length);
    lines.push(`export const ${exportName} = '${value}' as const;`);
  }

  lines.push('');

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf-8');

  console.log(`Generated ${path.relative(ROOT, OUT_FILE)} with ${publicVars.length} variable(s) (skipped ${Object.keys(vars).length - publicVars.length})`);
}

generate();
